apiVersion: v1
kind: Service
metadata:
  name: paas-mysql
  namespace: newtouchone
  labels:
    instanceId: paas-mysql
    paas: paas
  annotations:
    kubernetesReverseproxy : '{"hosts":[{"nodePort":31796,"tcp":true}]}'
spec:
  selector:
    instanceId: paas-mysql
  type: NodePort
  ports:
  - port: 3306
    nodePort: 31796
