apiVersion: v1
kind: Service
metadata:
  name: paas-redis
  namespace: newtouchone
  labels:
    instanceId: paas-redis
    paas: paas
  annotations:
    kubernetesReverseproxy : |
      {"hosts":[{"nodePort":32322,"tcp":"true"}]}
spec:
  selector:
    instanceId: paas-redis
  type: NodePort
  ports:
  - port: 6379
    nodePort: 32322
