apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: prometheus
  name: prometheus
  namespace: monitor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: prometheus-server
    spec:
      containers:
      - name: prometheus
        image: 172.21.7.11:5000/newtouchone/prometheus:v1.7.1
        command:
        - "/bin/prometheus"
        args:
        - "-config.file=/etc/prometheus/prometheus.yml"
        - "-storage.local.path=/prometheus"
        - "-storage.local.retention=24h"
        ports:
        - containerPort: 9090
          protocol: TCP
        volumeMounts:
        - mountPath: "/prometheus"
          name: data
        - mountPath: "/etc/prometheus"
          name: prometheus-config-volume
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 2500Mi
      serviceAccountName: prometheus
      serviceAccount: prometheus
      volumes:
      - emptyDir: {}
        name: data
      - name: prometheus-config-volume
        configMap:
          name: prometheus-config
          items:
            - key: prometheus.yml
              path: prometheus.yml
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetesReverseproxy: '{"hosts": [{"host": "prometheus.one2.newtouch.com","http": "true", "port": "80","nodePort":"30090"}]}'
  labels:
    name: prometheus
  name: prometheus
  namespace: monitor
spec:
  ports:
  - nodePort: 30090
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    name: prometheus-server
  sessionAffinity: None
  type: NodePort